services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CLOUD_ID: ${CLOUD_ID}
        FOLDER_ID: ${FOLDER_ID}
        YC_TOKEN: ${YC_TOKEN}
        SERVICE_ACCOUNT_NAME: ${SERVICE_ACCOUNT_NAME}
        FUNCTION_NAME: ${FUNCTION_NAME}
        TRIGGER_NAME: ${TRIGGER_NAME}
        BUCKET_NAME: ${BUCKET_NAME}
    ports:
      - "8000:8000"
    env_file:
      - .env